### PR TITLE
add type definition

### PR DESCRIPTION
**Pull request by taoqf**
Thanks @linxiaowu66 , I make some change from https://github.com/ustbhuangyi/better-scroll/issues/300

### CODE REVIEW

**Comment by taoqf** [comment]
@ustbhuangyi , 可否抽时间看看这个？我现在就需要用到它。我做了一些简单的测试，是可以用的。但里面的参数方法因为我刚接触，并不十分了解，是从 @linxiaowu66 提交的代码中拿来的。非常感谢.

**Comment by taoqf** [comment]
@ustbhuangyi done.

**Comment by taoqf** [comment]
@ustbhuangyi Could you please figer me out what was wrong with my commit?

> An error occurred while generating the build script.

**Comment by taoqf** [comment]
it seems travis ci failed again.

**Comment by ustbhuangyi** [comment]
I have no idea either, maybe the travis-ci's bug.

**Comment by taoqf** [comment]
@ustbhuangyi  then could u plz just ignore the tests and merge this pr?

**Comment by taoqf** [comment]
it seems travis ci has met a big bug now, my project get the same error.

**Comment by taoqf** [comment]
thanks

**Comment by taoqf** [comment]
btw, when will this would be published to npm?

**Comment by ustbhuangyi** [comment]
this week

**Comment by taoqf** [comment]
OK, thanks again.

**Pull request merged**
