### PR TITLE
Easier Code Contributions.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi.

I work for Gitpod(an online Open Source VS Code like IDE which is free for Open Source) and we're currently on a mission to simplify contributors/maintainers onboarding for cool Open Source projects.

This Pr adds Gitpod config to the repo to fully automate the dev setup for this project i.e with this config anyone interested in contributing to this project would be able to start a workspace where it will automatically:

- clone the `better-scroll` repo.
- install all of the dependencies.
- run `yarn vue:dev`,
- run `yarn docs:build` and `yarn docs:dev`.

This way anyone interested in contributing can start straight away without any friction.

You can give it a try on my fork of the repo via the following link:
 
https://gitpod.io/#https://github.com/nisarhassan12/better-scroll

This is how it looks:

image

A lot of projects out there are already using Gitpod to simplify contributors/maintainers onboarding experience some of them are:

 -  https://github.com/freeCodeCamp/freeCodeCamp
 -  https://github.com/facebook/docusaurus
 -  https://github.com/mozilla/pdf.js/
-  https://github.com/gatsbyjs/gatsby/
-  https://github.com/mobxjs/mobx/

You can find a brief list of them at https://contribute.dev

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Hi. @theniceangel It's totally fine that you closed the Pr but would you please like to tell me why you closed it? Thanks

**Comment by theniceangel** [comment]
@nisarhassan12 It seems that few people will use automate workflow, but if you want this pr to be merged, you can fix conflicts, and then i will merge it.

**Comment by nisarhassan12** [comment]
Thanks. I have resolved the conflicts.

**Comment by theniceangel** [comment]
@nisarhassan12 Thank you for your PR.

**Pull request merged**
